STUDIO-15840: modify import sdk project wizard
mulesoft/mule-tooling-sdk pull request #13
Opened 2020-12-18 14:52 UTC by camilaserra5

![image](https://user-images.githubusercontent.com/30216841/102622624-0d21a600-4120-11eb-9628-71db049f41c6.png)
![image](https://user-images.githubusercontent.com/30216841/102622650-190d6800-4120-11eb-908b-9fc7b19e6eb8.png)

2020-12-18 15:08 UTC, srialMule approved these changes

2020-12-28 22:07 UTC, srialMule requested changes

2020-12-28 22:07 UTC, srialMule commented on org.mule.tooling.sdk/src/org/mule/tooling/sdk/wizards/SDKImportProjectAction.java
> +            return ImportActionResult.withException(null);
I'm not sure if this is ok, the intention with this seems to be to print the trace of CoreException and IOException and continue to ignore them, other kinds of exceptions will fall in the second try and catch block

2020-12-30 13:03 UTC, camilaserra5 commented on org.mule.tooling.sdk/src/org/mule/tooling/sdk/SDKProjectAdapterFactory.java
> +        }, null);
the run(VoidCallabel) does not return anything, so that's why I need this one

2020-12-30 14:58 UTC, srialMule submitted a review, later dismissed

2020-12-30 15:46 UTC, mdaloia commented on org.mule.tooling.sdk/src/org/mule/tooling/sdk/impl/model/ConnectorProjectKind.java
> +        return project.hasNature("org.mule.tooling.sdk.sdkNature");
Wasn't already defined a constant for this value?

2020-12-30 15:46 UTC, mdaloia commented on org.mule.tooling.sdk/src/org/mule/tooling/sdk/wizards/SDKImportProjectAction.java
> +    }
Shouldn't it have the UpgradingLock like in https://github.com/mulesoft/mule-tooling-sdk/pull/17/files/caca16e74a159b436f1dab5b47b58e4a0fca0458#diff-71a838d30c5ab01a7efef5ffba7648af1e3dc44200a1d808414e20538a86b218R41 ?

2020-12-30 17:37 UTC, srialMule approved these changes

2020-12-30 17:37 UTC, merged