add first veresion jenkinsfiles
mulesoft/mule-tooling-sdk pull request #4
Opened 2020-11-19 14:22 UTC by camilaserra5

2020-11-19 14:53 UTC, mdaloia requested changes

2020-11-19 14:53 UTC, mdaloia commented on build.jenkinsfile
> +    maven 'M3.6.0'
It would be better to use a Maven Wrapper on the project so we do not depend on the jenkins environment and we can control it... for example use 3.6.3 which is the latest one

2020-11-19 14:53 UTC, mdaloia commented on build.jenkinsfile
> +@Library(['studio-utils@master', 'studio-slack@master'])
studio-slack seems to not be needed as it is not used

2020-11-19 14:53 UTC, mdaloia commented on build.jenkinsfile
> +        if (isUnix()) {
maybe we can use a `when` block with an `expression` using the `isUnix()` instead of this `if`... the advantage of this is that on the UI it is shown clearly that it is skipped (see [this article](https://medium.com/@MichaKutz/conditionals-in-a-declarative-pipeline-jenkinsfile-d1a4a44e93bb)).
Maybe we can also use a `parallel` to do the `scanSonarQubeWithMaven` and `scanNexusIQ`

2020-11-19 14:53 UTC, mdaloia commented on build.jenkinsfile
> +  }
remove it if not needed

2020-11-19 14:53 UTC, mdaloia commented on release.jenkinsfile
> +@Library(['studio-utils@master', 'studio-slack@master'])
idem... `studio-slack` seems not to be used

2020-11-19 14:53 UTC, mdaloia commented on release.jenkinsfile
> +      copyArtifacts(projectName: "Studio/Mule-Tooling-Sdk/${params.branch}", selector: latestSavedBuild());
Shouldn't we need to declare the parameter `branch`?

2020-11-19 14:53 UTC, mdaloia commented on release.jenkinsfile
> +      }
Wouldn't it be better if it is part of the `Preparation` stage?

2020-11-19 14:53 UTC, mdaloia commented on release.jenkinsfile
> +        branch 'release/1.0.x'
Maybe it will be better to leave it as: `release/*` so it is more future-proof

2020-11-19 14:53 UTC, mdaloia commented on build.jenkinsfile
> +        buildWithMaven("clean deploy -file org.mule.tooling.sdk.releng/pom.xml -Pamazon -Dbranch=env.BRANCH_NAME")
beware that the proper maven option is `-f` or `--file` (not `-file`)

2020-11-19 14:53 UTC, mdaloia commented on release.jenkinsfile
> +      buildWithMaven("clean deploy -file org.mule.tooling.sdk.releng/pom.xml -Pstage")
idem about `-file`

2020-11-19 14:53 UTC, mdaloia commented on release.jenkinsfile
> +        buildWithMaven("clean install -Prelease")
I prefer consistency with the rest, so I would use the `--file` to point to the pom.xml we want to build

2020-11-19 14:53 UTC, mdaloia commented on release.jenkinsfile
> +  stage('Update Site Production') {
Idea: maybe we can use the parallel for upload to staging and prod (like it is shown on the mentioned article)

2020-11-19 15:10 UTC, camilaserra5 commented on build.jenkinsfile
> +        buildWithMaven("clean deploy -file org.mule.tooling.sdk.releng/pom.xml -Pamazon -Dbranch=env.BRANCH_NAME")
https://github.com/mulesoft/tooling-jenkins-utils/blob/master/vars/deployStudioUpdateSitePipeline.groovy#L41
😮😮😮😮😮😮

2020-11-19 15:19 UTC, camilaserra5 commented on release.jenkinsfile
> +  stage('Update Site Production') {
But I thought this as: 
1. deploy to staging
2. do some manual tests
3. confirm to deploy to prod
4. deploy it
How would this work in parallel?

2020-11-19 15:50 UTC, mdaloia commented on release.jenkinsfile
> +  stage('Update Site Production') {
In that case there won't be much benefit doing it in parallel (the ask stage could be there, but the idea was to trigger it while it is still uploading staging).
Another option could be to have parameterized the environment to deploy.
But you can leave as it is for now.

(we should avoid as much as possible having "some manual tests" jejej)

2020-11-19 15:52 UTC, mdaloia commented on release.jenkinsfile
> +        expression { ${params.branch} ==~ /release\/\d+\.\d+\.\d+/
why this way instead of something like?:
https://github.com/mulesoft/Mule-Tooling/blob/a2e76497442cebd431191460e8ec973d7316cf7e/Studio-7-Deploy-Update-Site.jenkinsfile#L65

2020-11-19 22:37 UTC, mdaloia commented on build.jenkinsfile
> +        isUnix()
Have your tried it? If I'm not wrong I think that it needs to be surrounded by an `expression { }` block

2020-11-19 22:37 UTC, mdaloia commented on build.jenkinsfile
> +              "target" : "org.mule.tooling.sdk/target/*.jar"
Sorry that didn't see this before, but shouldn't it be `org.mule.tooling.sdk.updatesite/target/org.mule.tooling.sdk.updatesite-*.zip` (based on [Mule-Tooling](https://github.com/mulesoft/Mule-Tooling/blob/a2e76497442cebd431191460e8ec973d7316cf7e/Studio-Nexus-Scan.jenkinsfile#L15))

2020-11-19 22:37 UTC, mdaloia commented on build.jenkinsfile
> +              "buildCommandLine": params.buildCommandLine,
This parameter `buildCommandLine` seems not be defined here, but seems not being used neither on `scanNexusIQ` method (which is correct... it should only scan an already built app/lib).

2020-11-19 22:37 UTC, mdaloia commented on build.jenkinsfile
> +            scanSonarQubeWithMaven("mule-tooling-sdk")
Recheck this... Unless there is something that I'm missing then the method should be `scanSonarQube` which receives 2 parameters: `projectKey` and `branch`

2020-11-20 19:03 UTC, mdaloia approved these changes

2020-11-20 19:04 UTC, merged